### ISSUE TITLE
Bug in ReviewsClient

### ISSUE THREAD

**Issue by arthyarthy** [petrbroz/forge-sdk-python#24]
The class ReviewsClient is not working properly.
The call `reviews=Reviews.get_reviews(project_id)` produces an error where `Reviews=ReviewsClient(OAuthTokenProvider(client_id, client_secret))`

**Comment by COWI-MI** [comment]
Please see https://github.com/petrbroz/forge-sdk-python/issues/23
The endpoint has not been released, and was removed from this repo.
