### ISSUE TITLE
adding support for data and docs endpoints

### ISSUE THREAD

**Issue by Magnus-COWI** [petrbroz/forge-sdk-python#8]
Hi @petrbroz

I am looking for support for Naming Standard, custom attributes and more.
I created pull request #7 that adds some of those API calls.

Let me know what you think about the structure and what else.
I am happy to help 🙂

**Comment by petrbroz** [comment]
Hi @Magnus-COWI, your contribution is very much appreciated :) I've added a couple of notes to the PR (with just a minor request for changing the file/class structure), and once it's cleared I'd be happy to merge it.
